gridWorkingDir:			workingdirESD
gridOutputDir:			outputdir_13d_kEMCEGA_kINT7_mannualMode_greenlight_nonLinCorr
aliPhysicsVersion:		vAN-20201205_ROOT6-1
package:			fastjet::v3.2.1_1.024-alice3-94
package:			boost::v1.72.0-alice2-7
gridDataDir:			/alice/data/2013/LHC13d
dataPattern:			/pass4/*/AliESDs.root
runPrefix:			000
runNumber:			[195872, 195871, 195867, 195831, 195829, 195787, 195783, 195767, 195760, 195724]
emcalCorrection:		emcal_correction_nonLin.yaml
emcalGeometryFilename:		geometry_2015.root
emcalLocal2MasterFilename:	EMCALlocal2master.root
splitMaxInputFileNumber:	30.0
isMC:				false
isEmbed:			false
