gridWorkingDir:			workingdirESD
gridOutputDir:			outputdir_13f_part3_kEMCEGA_kINT7_mannualMode_greenlight_nonLinCorr
aliPhysicsVersion:		vAN-20201205_ROOT6-1
package:			fastjet::v3.2.1_1.024-alice3-94
package:			boost::v1.72.0-alice2-7
gridDataDir:			/alice/data/2013/LHC13f
dataPattern:			/pass4/*/AliESDs.root
runPrefix:			000
#runNumber:			[197091, 197027, 197015, 197012, 197011, 197003, 196974, 196973, 196972, 196967]
emcalCorrection:		emcal_correction_nonLin.yaml
emcalGeometryFilename:		geometry_2015.root
emcalLocal2MasterFilename:	EMCALlocal2master.root
splitMaxInputFileNumber:	30.0
isMC:				false
isEmbed:			false
