gridWorkingDir:			workingdirESD_wNL_wSCaler
gridOutputDir:			outputdir_13f_part1_kEMCEGA_kINT7_mannualMode_greenlight_nonLinCorr_scalerCorr
aliPhysicsVersion:		vAN-20211022_ROOT6-1
package:			fastjet::v3.2.1_1.024-alice3-109
package:			boost::v1.74.0-16
#aliPhysicsVersion:		vAN-20201205_ROOT6-1
#package:			fastjet::v3.2.1_1.024-alice3-94
#package:			boost::v1.72.0-alice2-7
gridDataDir:			/alice/data/2013/LHC13f
dataPattern:			/pass4/*/AliESDs.root
runPrefix:			000
runNumber:			[197342, 197341, 197302, 197300, 197299, 197298, 197297, 197296, 197260, 197258]
emcalCorrection:		emcal_correction_nonLin_scalers_pPb.yaml
emcalGeometryFilename:		geometry_2015.root
emcalLocal2MasterFilename:	EMCALlocal2master.root
splitMaxInputFileNumber:	20.0
isMC:				false
isEmbed:			false
